In [2]:
import torch
torch.__version__

'2.0.1+cu117'

# Tensor Manipulation

In [4]:
tensor = torch.tensor([1, 2, 3])

In [6]:
tensor * 10

tensor([10, 20, 30])

In [7]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [8]:
torch.matmul(tensor, tensor)

tensor(14)

In [12]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)


tensor(14)
CPU times: total: 0 ns
Wall time: 1.99 ms


In [13]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [15]:
torch.matmul(torch.rand(2, 2), torch.rand(2, 3))

tensor([[1.1588, 0.6846, 1.0547],
        [0.5795, 0.2594, 0.4787]])

In [16]:
matrix_A = torch.tensor([[1, 2],
                         [2, 3],
                         [4, 5]])
matrix_B = torch.tensor([[6, 7],
                         [8, 9],
                         [10, 11]])

In [17]:
torch.mm(matrix_A, matrix_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [18]:
matrix_B.T

tensor([[ 6,  8, 10],
        [ 7,  9, 11]])

In [19]:
matrix_B

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [20]:
torch.mm(matrix_A, matrix_B.T)

tensor([[20, 26, 32],
        [33, 43, 53],
        [59, 77, 95]])

### Tensor Aggregations

In [21]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [25]:
torch.max(x), x.max

(tensor(90), <function Tensor.max>)

In [29]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [31]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [34]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
x = x - 1
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [38]:
x.argmin()

tensor(0)

In [39]:
x.argmax()

tensor(9)

## Reshaping, View, Stacking, Squeezing, Unsqueezung, Permute

In [40]:
import torch

In [41]:
x = torch.arange(1.0, 10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
# Add Extra dimentions
# reshaped_x = x.reshape(1, 7) ## ERROR: shape '[1, 7]' is invalid for input of size 9
reshaped_x = x.reshape(3, 3)
print(reshaped_x, reshaped_x.shape)
reshaped_x = x.reshape(1, 9)
reshaped_x, reshaped_x.shape

tensor([[5., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]) torch.Size([3, 3])


(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Change the view
z = x.view(1, 9)
z, x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# The  tensor view share the same memory of the original tensor, 
# changing tensor or its view affect each other
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [58]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [62]:
# Squeeze tensor
print(reshaped_x)
print(reshaped_x.shape)
squeezed_x = reshaped_x.squeeze()
print(squeezed_x)
print(squeezed_x.shape)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])
tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [70]:
# Unsqueeze: add extra dimension to a tensor at a specific position
unsqueezed_x = squeezed_x.unsqueeze(dim=0)
print(unsqueezed_x, unsqueezed_x.shape)

unsqueezed_x = squeezed_x.unsqueeze(dim=1)
unsqueezed_x, unsqueezed_x.shape

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]) torch.Size([1, 9])


(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [75]:
# torch.permute
original_x = torch.rand(224, 224, 3) # width, height, colors channels of an image
#permuted_x = original_x.permute(dims=(2, 0, 1))
permuted_x = original_x.permute((2, 0, 1))


print(f"Original x: {original_x.shape}")
print(f"Permuted x: {permuted_x.shape}")
# notice: permute is a view of the original tensor

Original x: torch.Size([224, 224, 3])
Permuted x: torch.Size([3, 224, 224])


In [77]:
original_x[0, 0, 0] = 999
original_x[0, 0, 0], permuted_x[0, 0, 0]


(tensor(999.), tensor(999.))

### Indexing (Selecting data from tensors)
Indexing in PyTorch is similar to undexing in NumPy

In [78]:
import torch

In [79]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [88]:
print(x[0])
print(x[0, 0])
print(x[0][0])
print(x[0, 0, 0])
print(x[0, 2, 2])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor([1, 2, 3])
tensor(1)
tensor(9)


In [96]:
print(x[:])
print(x[::])
print(x[:, 0]) # tensor([[1, 2, 3]])
print(x[:, 1]) # tensor([[4, 5, 6]])
print(x[::, 0]) # tensor([[1, 2, 3]])
print(x[:,:, 0]) # tensor([[1, 4, 7]])
print(x[:,:, 1]) # tensor([[2, 5, 8]])
print(x[:,:, :, 0]) # Error: too many indices for tensor of dimension 3

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3]])
tensor([[4, 5, 6]])
tensor([[1, 2, 3]])
tensor([[1, 4, 7]])
tensor([[2, 5, 8]])


IndexError: too many indices for tensor of dimension 3

In [97]:
# Get all values of the 0th and 1st dimension but only index 1 2nd dimenstion
x[:, :, 1]

tensor([[2, 5, 8]])

In [98]:
# get the all values of the 0 dimension but 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [99]:
# get index 0 of 0th and 1st dimensions and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [100]:
x[0, :, 1]

tensor([2, 5, 8])

In [101]:
x[0, :, :]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### PyTorch Tensors and NumPy

In [102]:
import torch
import numpy as np

In [103]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproducibility 

In [105]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4437, 0.2967, 0.0937, 0.3180],
        [0.6438, 0.2057, 0.7839, 0.2580],
        [0.3655, 0.6964, 0.6491, 0.3307]])
tensor([[0.6300, 0.5779, 0.1668, 0.5390],
        [0.6777, 0.5474, 0.0455, 0.9099],
        [0.9745, 0.8452, 0.1345, 0.6057]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [106]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [107]:
torch.cuda.is_available()

False

In [108]:
print(torch.version.cuda)

11.7
